name: week_03_artello
description: Artello
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.7.0
  theme_tailor_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  theme_tailor: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
